services:
  ipfs-api:
    build: .
    container_name: ipfs-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    volumes:
      - /opt/apps/data/ipfs/uploads:/app/uploads
      - /opt/apps/data/ipfs/cache:/app/cache
      - ipfs-cache:/app/.cache
      - /opt/apps/data/logs/ipfs:/app/logs
      - ./production.env:/app/.env:ro
    networks:
      - ipfs-network

network:
  ipfs-network:
    driver: bridge

volumes:
  ipfs-cache: